# Generated by Django 4.2.25 on 2026-01-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
