# Generated by Django 4.2.25 on 2026-01-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_skillsmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mindmap', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
