# Generated by Django 4.2.25 on 2026-01-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('ug_degree', models.CharField(max_length=150)),
                ('ug_university', models.CharField(max_length=200)),
                ('ug_years', models.CharField(max_length=20)),
                ('pg_degree', models.CharField(max_length=150)),
                ('pg_university', models.CharField(max_length=200)),
                ('pg_years', models.CharField(max_length=20)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('photo_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
