# Generated by Django 5.1.3 on 2026-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Masters", "0008_hirerequest_phone_projectrequest_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginprofile",
            name="view_time_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
